spring:
  application:
    name: TransactionsAndConcurrency
  datasource:
    url: jdbc:h2:mem:db;LOCK_TIMEOUT=10000 # In-memory database
    driverClassName: org.h2.Driver
    username: admin
    password: "admin"

  h2:
    console:
      enabled: true # Enable H2 console
      path: /h2-console # Path to access the H2 console in browser

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # Automatically update database schema

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

